/* The following code was generated by JFlex 1.7.0 */

 package Analizadores;
import java.util.LinkedList;
import java_cup.runtime.*;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>C:/Users/saral/OneDrive/Documentos/GitHub/TFG/src/Analizadores/AnalizadorLexico.flex</tt>
 */
public class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int estado1 = 2;
  public static final int estado2 = 4;
  public static final int estado3 = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
    41, 41, 41, 41, 41, 41, 41, 41, 41, 36, 37, 39, 39, 38, 41, 41, 
    41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 
    14, 41, 34, 41, 41,  7, 33, 21, 17, 16, 22, 35,  8,  9, 10, 13, 
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6, 11,  5, 26, 32, 28, 41, 
    41, 15,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3, 
     3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3, 23, 41, 23, 41, 41, 
    41,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 41, 41, 41, 41, 41, 
    41, 41, 41, 41, 41, 39, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 
    41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 
    41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 27, 20, 41, 41, 29, 41, 
    30, 41, 41, 41, 41, 19, 41, 25, 41, 41, 31, 18, 41, 41, 41, 41, 
    41,  4, 41, 41, 41, 41, 41, 41, 41,  4, 41, 41, 41,  4, 41, 41, 
    41,  4, 41,  4, 41, 41, 41, 41, 41, 41,  4, 41, 41, 41, 41, 24, 
    41,  1, 41, 41, 41, 41, 41, 41, 41,  1, 41, 41, 41,  1, 41, 41, 
    41,  1, 41,  1, 41, 41,  1, 41, 41, 41,  1, 41,  1, 41, 41, 41
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\3\0\1\2\2\1\1\3\1\2\3\1\1\4"+
    "\1\5\1\6\1\2\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\2\35\1\36\1\37\1\40\2\41\1\42\6\41"+
    "\1\0\1\41\1\43\1\41\1\44\3\1\1\3\1\0"+
    "\4\3\1\1\2\0\1\1\2\0\2\1\10\0\1\42"+
    "\1\0\4\42\12\0\1\1\4\0\4\3\2\0\1\1"+
    "\1\0\1\1\5\0\4\42\5\0\1\1\2\3\2\0"+
    "\2\3\1\0\3\1\1\0\2\42\2\0\2\42\4\0"+
    "\1\3\2\0\2\3\1\1\1\42\2\0\2\42\1\0"+
    "\1\3\1\0\1\3\1\42\1\0\1\42\1\0\1\3"+
    "\1\0\1\42\2\3\2\42\1\0\1\3\1\0\1\42"+
    "\1\3\1\42\1\3\1\42\2\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\374\0\u0126"+
    "\0\u0150\0\250\0\u017a\0\u01a4\0\250\0\u01ce\0\250\0\u01f8"+
    "\0\250\0\u0222\0\250\0\250\0\250\0\u01f8\0\250\0\250"+
    "\0\250\0\250\0\250\0\250\0\250\0\250\0\250\0\250"+
    "\0\250\0\250\0\250\0\250\0\250\0\250\0\250\0\u024c"+
    "\0\250\0\250\0\250\0\u0276\0\u02a0\0\u02ca\0\u02f4\0\u031e"+
    "\0\u0348\0\u0372\0\250\0\u039c\0\u03c6\0\u03f0\0\250\0\u03c6"+
    "\0\250\0\u0222\0\u041a\0\u0444\0\u046e\0\u0498\0\u0498\0\u04c2"+
    "\0\u04ec\0\u0516\0\u0540\0\u056a\0\u0594\0\u05be\0\u05e8\0\u0612"+
    "\0\u063c\0\u0666\0\u01f8\0\u0690\0\u0276\0\u031e\0\u0372\0\u03f0"+
    "\0\u06ba\0\u06e4\0\u070e\0\u0738\0\u0738\0\u0762\0\u078c\0\u07b6"+
    "\0\u07e0\0\u080a\0\u0834\0\u085e\0\u0888\0\u08b2\0\u08dc\0\u0906"+
    "\0\u0930\0\u095a\0\u0984\0\u09ae\0\u09d8\0\u0a02\0\u0a2c\0\250"+
    "\0\u0a56\0\u0a80\0\u0aaa\0\u05be\0\u0ad4\0\u0afe\0\u0b28\0\u0b52"+
    "\0\u0b7c\0\u0ba6\0\u0bd0\0\u0bfa\0\u0c24\0\250\0\u0c4e\0\u0c78"+
    "\0\u0ca2\0\u0ccc\0\u0cf6\0\u0d20\0\u0d4a\0\u0d74\0\u0d9e\0\u0dc8"+
    "\0\u0df2\0\u0e1c\0\u0e46\0\u0e70\0\u0e9a\0\u0ec4\0\u0ec4\0\u0eee"+
    "\0\u0f18\0\u0f42\0\u0f6c\0\u0f96\0\u0fc0\0\u0fea\0\u1014\0\u103e"+
    "\0\u1068\0\u1092\0\u10bc\0\u10e6\0\u1110\0\u113a\0\u1164\0\u118e"+
    "\0\u11b8\0\u11e2\0\u120c\0\u1236\0\u1260\0\u128a\0\u12b4\0\u12de"+
    "\0\u1308\0\u118e\0\u1332\0\u135c\0\u128a\0\u1386\0\u13b0\0\u13da"+
    "\0\u1404\0\u142e\0\u1458\0\u1482\0\u14ac\0\u14d6\0\u1500\0\u152a"+
    "\0\u1554\0\u157e\0\u15a8\0\u15d2\0\u15fc\0\u1626\0\u15a8\0\u15d2";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\12\1\17\1\20\1\21\1\22\1\10"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\2\47\1\50\2\0\1\5"+
    "\11\51\1\52\7\51\1\53\30\51\1\0\1\54\1\55"+
    "\1\56\1\57\1\60\1\61\1\62\1\63\1\64\1\60"+
    "\1\63\1\65\1\63\1\66\1\56\1\67\2\63\1\70"+
    "\24\63\1\0\21\63\1\71\31\63\53\0\2\6\2\0"+
    "\1\12\3\0\1\14\1\12\1\14\2\0\1\72\34\0"+
    "\1\6\1\73\2\0\1\12\3\0\1\74\1\75\1\14"+
    "\2\0\1\72\34\0\1\76\1\77\1\100\2\0\1\101"+
    "\3\0\1\102\4\0\1\100\33\0\2\76\54\0\1\12"+
    "\1\103\1\14\1\104\1\105\1\106\3\0\1\72\40\0"+
    "\1\12\4\0\1\12\3\0\1\72\36\0\2\107\12\0"+
    "\1\107\33\0\2\110\50\0\2\111\2\107\1\12\1\103"+
    "\1\14\1\0\1\112\1\12\1\14\1\113\1\0\1\72"+
    "\1\114\3\0\1\113\73\0\1\47\5\0\2\115\2\0"+
    "\1\116\3\0\1\117\1\116\1\117\2\0\1\120\1\0"+
    "\1\67\32\0\1\115\1\121\2\0\1\116\3\0\1\122"+
    "\1\123\1\117\2\0\1\120\1\0\1\67\32\0\1\124"+
    "\1\125\1\126\2\0\1\127\3\0\1\130\4\0\1\126"+
    "\33\0\2\124\65\0\1\131\1\0\1\67\36\0\1\116"+
    "\1\132\1\117\1\133\1\134\1\135\3\0\1\120\1\0"+
    "\1\67\36\0\1\116\4\0\1\116\3\0\1\120\1\0"+
    "\1\67\34\0\2\136\12\0\1\136\33\0\2\137\50\0"+
    "\2\140\2\136\1\116\1\132\1\117\1\0\1\141\1\116"+
    "\1\117\1\65\1\0\1\120\1\142\1\67\2\0\1\65"+
    "\27\0\1\6\1\143\2\0\1\12\3\0\1\74\1\12"+
    "\1\14\2\0\1\72\36\0\1\144\1\0\1\12\4\0"+
    "\1\12\3\0\1\72\1\144\34\0\2\145\13\0\1\145"+
    "\33\0\2\76\2\146\4\0\1\147\1\0\1\147\3\0"+
    "\1\146\34\0\1\150\1\151\2\0\1\101\10\0\1\151"+
    "\40\0\1\152\45\0\1\145\1\153\13\0\1\153\37\0"+
    "\1\12\1\103\1\14\1\104\1\154\1\106\3\0\1\72"+
    "\41\0\1\155\46\0\1\144\2\0\1\156\10\0\1\144"+
    "\40\0\1\156\44\0\2\6\64\0\1\157\35\0\2\111"+
    "\2\0\1\12\3\0\1\160\1\12\1\160\2\0\1\72"+
    "\36\0\2\107\1\12\4\0\1\12\3\0\1\72\1\107"+
    "\33\0\2\6\13\0\1\14\34\0\1\115\1\161\2\0"+
    "\1\116\3\0\1\122\1\116\1\117\2\0\1\120\1\0"+
    "\1\67\34\0\1\162\1\0\1\116\4\0\1\116\3\0"+
    "\1\120\1\162\1\67\33\0\2\163\12\0\1\131\1\163"+
    "\1\67\32\0\2\124\2\164\4\0\1\165\1\0\1\165"+
    "\3\0\1\164\34\0\1\166\1\167\2\0\1\127\10\0"+
    "\1\167\40\0\1\170\45\0\1\163\1\171\13\0\1\171"+
    "\52\0\1\67\36\0\1\116\1\132\1\117\1\133\1\172"+
    "\1\135\3\0\1\120\1\0\1\67\37\0\1\173\46\0"+
    "\1\162\2\0\1\174\10\0\1\162\40\0\1\174\7\0"+
    "\1\131\1\0\1\67\32\0\2\115\64\0\1\175\35\0"+
    "\2\140\2\0\1\116\3\0\1\176\1\116\1\176\2\0"+
    "\1\120\1\0\1\67\34\0\2\136\1\116\4\0\1\116"+
    "\3\0\1\120\1\136\1\67\32\0\2\115\13\0\1\117"+
    "\34\0\1\6\1\177\2\0\1\12\3\0\1\74\1\12"+
    "\1\14\2\0\1\72\36\0\1\200\13\0\1\200\44\0"+
    "\1\201\40\0\2\202\52\0\2\146\4\0\1\203\5\0"+
    "\1\146\34\0\1\150\1\204\2\0\1\101\10\0\1\204"+
    "\40\0\1\150\55\0\1\205\45\0\1\155\2\0\2\154"+
    "\44\0\1\12\1\156\1\0\1\206\1\0\1\207\3\0"+
    "\1\72\34\0\2\210\50\0\2\211\2\0\1\12\4\0"+
    "\1\12\3\0\1\72\34\0\1\115\1\212\2\0\1\116"+
    "\3\0\1\122\1\116\1\117\2\0\1\120\1\0\1\67"+
    "\34\0\1\213\13\0\1\213\44\0\1\214\40\0\2\215"+
    "\52\0\2\164\4\0\1\216\5\0\1\164\34\0\1\166"+
    "\1\217\2\0\1\127\10\0\1\217\40\0\1\166\55\0"+
    "\1\220\45\0\1\174\51\0\1\173\2\0\2\172\44\0"+
    "\1\116\1\174\1\0\1\221\1\0\1\222\3\0\1\120"+
    "\1\0\1\67\32\0\2\223\50\0\2\224\2\0\1\116"+
    "\4\0\1\116\3\0\1\120\1\0\1\67\32\0\2\6"+
    "\2\0\1\12\3\0\1\74\1\12\1\14\2\0\1\72"+
    "\36\0\1\225\13\0\1\225\34\0\2\226\13\0\1\226"+
    "\33\0\2\202\6\0\1\227\1\0\1\227\41\0\2\146"+
    "\12\0\1\146\34\0\1\150\1\230\2\0\1\101\10\0"+
    "\1\230\34\0\1\226\1\231\13\0\1\231\40\0\1\232"+
    "\44\0\2\210\2\0\1\12\4\0\1\12\3\0\1\72"+
    "\34\0\2\211\2\0\1\12\3\0\1\227\1\12\1\227"+
    "\2\0\1\72\34\0\2\115\2\0\1\116\3\0\1\122"+
    "\1\116\1\117\2\0\1\120\1\0\1\67\34\0\1\233"+
    "\13\0\1\233\34\0\2\234\13\0\1\234\33\0\2\215"+
    "\6\0\1\235\1\0\1\235\41\0\2\164\12\0\1\164"+
    "\34\0\1\166\1\236\2\0\1\127\10\0\1\236\34\0"+
    "\1\234\1\237\13\0\1\237\40\0\1\240\51\0\1\240"+
    "\7\0\1\131\1\0\1\67\32\0\2\223\2\0\1\116"+
    "\4\0\1\116\3\0\1\120\1\0\1\67\32\0\2\224"+
    "\2\0\1\116\3\0\1\235\1\116\1\235\2\0\1\120"+
    "\1\0\1\67\34\0\1\150\13\0\1\150\44\0\1\241"+
    "\40\0\2\211\51\0\1\150\1\242\13\0\1\242\44\0"+
    "\1\243\44\0\1\12\1\232\3\0\1\12\3\0\1\72"+
    "\36\0\1\166\13\0\1\166\44\0\1\244\40\0\2\224"+
    "\51\0\1\166\1\245\13\0\1\245\44\0\1\246\44\0"+
    "\1\116\1\240\3\0\1\116\3\0\1\120\1\0\1\67"+
    "\33\0\2\247\13\0\1\247\34\0\1\247\1\250\13\0"+
    "\1\250\34\0\2\251\13\0\1\251\34\0\1\251\1\252"+
    "\13\0\1\252\44\0\1\253\51\0\1\254\51\0\1\255"+
    "\51\0\1\256\41\0\2\257\13\0\1\257\34\0\1\257"+
    "\1\260\13\0\1\260\34\0\2\261\13\0\1\261\34\0"+
    "\1\261\1\262\13\0\1\262\44\0\1\150\51\0\1\263"+
    "\51\0\1\166\51\0\1\264\42\0\1\265\13\0\1\265"+
    "\35\0\1\266\13\0\1\266\44\0\1\267\51\0\1\270"+
    "\37\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5712];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\3\0\1\11\4\1\1\11\2\1\1\11\1\1"+
    "\1\11\1\1\1\11\1\1\3\11\1\1\21\11\1\1"+
    "\3\11\7\1\1\11\1\1\1\0\1\1\1\11\1\1"+
    "\1\11\4\1\1\0\5\1\2\0\1\1\2\0\2\1"+
    "\10\0\1\1\1\0\4\1\12\0\1\1\4\0\1\11"+
    "\3\1\2\0\1\1\1\0\1\1\5\0\1\11\3\1"+
    "\5\0\3\1\2\0\2\1\1\0\3\1\1\0\2\1"+
    "\2\0\2\1\4\0\1\1\2\0\4\1\2\0\2\1"+
    "\1\0\1\1\1\0\2\1\1\0\1\1\1\0\1\1"+
    "\1\0\5\1\1\0\1\1\1\0\5\1\2\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	StringBuffer aux = new StringBuffer();
     	int auxLinea = 0;
     	int auxColumna = 0;
	String varAux="";
	String posibleLF="";
	String acronimo="";
	FormaLargaWithAc acWLf=new FormaLargaWithAc ();
	


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {  return new Symbol(sym.EOF, null); 
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { posibleLF=yytext();
				yybegin(estado1);
				acWLf.clean();
				acWLf.setFormaLarga(posibleLF);
				System.out.println("lf");
            } 
            // fall through
          case 37: break;
          case 2: 
            { System.err.println("Error lexico: caracter no reconocido <" + yytext() + "> en la linea " + (yyline+1) 
	+ " y columna " + (yycolumn +1));
            } 
            // fall through
          case 38: break;
          case 3: 
            { return new Symbol(sym.acronimo,yyline +1, yycolumn +1,yytext());
            } 
            // fall through
          case 39: break;
          case 4: 
            { //Coma
				;
            } 
            // fall through
          case 40: break;
          case 5: 
            { //barra -
				System.out.println("Barra -");
				;
            } 
            // fall through
          case 41: break;
          case 6: 
            { //Simbolo dos puntos
				;
            } 
            // fall through
          case 42: break;
          case 7: 
            { //Barra / 
			;
            } 
            // fall through
          case 43: break;
          case 8: 
            { System.out.println("space");
            } 
            // fall through
          case 44: break;
          case 9: 
            { //Si detecta frases explicatorias entre parentesis
				;
            } 
            // fall through
          case 45: break;
          case 10: 
            { //Si hay acronimos en una frase no detectara el parentesis, pues al principio estaba en el estado 1
				yypushback(yytext().length());
				yybegin(estado1);
            } 
            // fall through
          case 46: break;
          case 11: 
            { //comillas latinas cierre
				;
            } 
            // fall through
          case 47: break;
          case 12: 
            { //Simbolo micro
				;
            } 
            // fall through
          case 48: break;
          case 13: 
            { //comillas latinas apertura
				;
            } 
            // fall through
          case 49: break;
          case 14: 
            { //comilla simple
				;
            } 
            // fall through
          case 50: break;
          case 15: 
            { //asterisco
				;
            } 
            // fall through
          case 51: break;
          case 16: 
            { //Corchetes 
				;
            } 
            // fall through
          case 52: break;
          case 17: 
            { //minúscula S aguda 
				;
            } 
            // fall through
          case 53: break;
          case 18: 
            { //Punto centrado
				;
            } 
            // fall through
          case 54: break;
          case 19: 
            { //Simbolo menor que
				;
            } 
            // fall through
          case 55: break;
          case 20: 
            { //a sufijo
				;
            } 
            // fall through
          case 56: break;
          case 21: 
            { //Simbolo mayor que
				;
            } 
            // fall through
          case 57: break;
          case 22: 
            { //Simbolo registro
				;
            } 
            // fall through
          case 58: break;
          case 23: 
            { //Simbolo grados
				;
            } 
            // fall through
          case 59: break;
          case 24: 
            { //Simbolo ordinal
				;
            } 
            // fall through
          case 60: break;
          case 25: 
            { //Simbolo igual
				;
            } 
            // fall through
          case 61: break;
          case 26: 
            { //Ampersan 
				;
            } 
            // fall through
          case 62: break;
          case 27: 
            { //Comilla "
				;
            } 
            // fall through
          case 63: break;
          case 28: 
            { //Sumatorio	
				;
            } 
            // fall through
          case 64: break;
          case 29: 
            { acronimo=""; posibleLF="";
            } 
            // fall through
          case 65: break;
          case 30: 
            { String b=yytext();
			if(b!=null){
				yypushback(b.length());
				acWLf.clean();
			}
			yybegin(YYINITIAL);
            } 
            // fall through
          case 66: break;
          case 31: 
            { ;
            } 
            // fall through
          case 67: break;
          case 32: 
            { yybegin(estado2);
		System.out.println("pa");
            } 
            // fall through
          case 68: break;
          case 33: 
            { if(yytext()!=null){
			yypushback(yytext().length());
			acWLf.clean();}
			yybegin(YYINITIAL);
            } 
            // fall through
          case 69: break;
          case 34: 
            { acronimo=yytext();
			acWLf.setAcronimo(acronimo);
			yybegin(estado3);
			System.out.println("ac");
            } 
            // fall through
          case 70: break;
          case 35: 
            { yybegin(YYINITIAL); acWLf.clean();
            } 
            // fall through
          case 71: break;
          case 36: 
            { yybegin(YYINITIAL);
		System.out.println("pc");
		//Cuidado si le paso el objeto en el sintactico lo usa como puntero y solo se guarda la ultima ocurrencia. Por ello new Object
		return new Symbol(sym.acWithLf,yyline+1,yycolumn+1,new FormaLargaWithAc(acWLf.getAcronimo(),acWLf.getFormaLarga()));
            } 
            // fall through
          case 72: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
